### PR TITLE
finalize user-facing elements(finalizer/tagging/labeling)

### LINKED ISSUE #1463: [v2] 2.0.0rc2 refuses to manage ingress in namespaces with long names
Hi,
   I'm testing out 2.0.0rc2 as we really need the ALB aggregation functionality.

   It appears that the reconciler can not handle namespace names that are within Kubernetes' 63-character limit. This seems to be because they are trying to include the namespace name in a much longer name. For example, for the namespace "b-bugfix-jh-dt-3120-clean-jenkins-run" (which isn't that long of a name, to be honest), it is prepending "alb.ingress.k8s.aws/" and suffixing the ingress name, ".ingress-external-dex-auth" onto another k8s object with a 63-character name limit, causing a crash.

    There has to be some way to label these things that doesn't involve concatenation. We already truncate our namespace names at 63 characters when created (they are the names of branches in git in our CI/CD pipeline):

```
{"level":"error","ts":1601497876.3211784,"logger":"controller-runtime.controller","msg":"Reconciler error","controller":"ingress","name":"rex-ingress-external-dex-auth","namespace":"b-bugfix-jh-dt-3120-clean-jenkins-run","error":"Ingress.extensions \"ingress-external-dex-auth\" is invalid: metadata.finalizers: Invalid value: \"alb.ingress.k8s.aws/b-bugfix-jh-dt-3120-clean-jenkins-run.ingress-external-dex-auth\": name part must be no more than 63 characters","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\t/go/pkg/mod/github.com/go-logr/zapr@v0.1.0/zapr.go:128\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.1/pkg/internal/controller/controller.go:235\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.1/pkg/internal/controller/controller.go:209\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.1/pkg/internal/controller/controller.go:188\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1\n\t/go/pkg/mod/k8s.io/apimachinery@v0.18.4/pkg/util/wait/wait.go:155\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil\n\t/go/pkg/mod/k8s.io/apimachinery@v0.18.4/pkg/util/wait/wait.go:156\nk8s.io/apimachinery/pkg/util/wait.JitterUntil\n\t/go/pkg/mod/k8s.io/apimachinery@v0.18.4/pkg/util/wait/wait.go:133\nk8s.io/apimachinery/pkg/util/wait.Until\n\t/go/pkg/mod/k8s.io/apimachinery@v0.18.4/pkg/util/wait/wait.go:90"}
```

### PR DESCRIPTION
**Pull request by M00nF1sh**
# finalize all user-facing elements, details below:
### For AWS resources created by this controller, the tagging strategy is as follows:
 * `elbv2.k8s.aws/cluster: cluster-name` will be applied on all AWS resources.
 * `ingress.k8s.aws/stack: stack-id` will be applied on all AWS resources provisioned for Ingress resources:
   * For explicit IngressGroup, `stack-id` will be `groupName`
   * For implicit IngressGroup, `stack-id` will be `namespace/ingressName`
 * `ingress.k8s.aws/resource: resource-id` will be applied on all AWS resources provisioned for Ingress resources:
   * For LoadBalancer, `resource-id` will be `LoadBalancer`
   * For Managed LB SecurityGroup, `resource-id` will be `ManagedLBSecurityGroup`
   * For TargetGroup, `resource-id` will be `namespace/ingressName-serviceName:servicePort`
 * `service.k8s.aws/stack: stack-id` will be applied on all AWS resources provisioned for Service resources:
   * `stack-id` will be `namespace/serviceName`
 * `service.k8s.aws/resource: resource-id` will be applied on all AWS resources provisioned for Service resources:
   * For LoadBalancer, `resource-id` will be `LoadBalancer`
   * For TargetGroup, `resource-id` will be `namespace/serviceName:servicePort`
### For AWS resources created by this controller, the naming strategy is as follows:
1. LoadBalancer:
   * For explicit IngressGroup: `k8s-%.17s{groupName}-%.10s{hash}`
   * For implicit IngressGroup & Service: `k8s-%.8s{namespace}%.8s{name}-%.10s{hash}`
2. TargetGroup: `k8s-%.8s{namespace}%.8s{name}-%.10s{hash}`
### For K8s resources created by this controller, the labelling strategy is as follows:
Note: We break "stack" into "stack-namespace" and "stack-name" for  implicit IngressGroup and Service since label value must be within 63 characters.
 * For explicit IngressGroup, the following tags will be applied on all K8s resources:
   * `ingress.k8s.aws/stack: groupName`
 * For implicit IngressGroup, the following tags will be applied on all K8s resources: 
   * `ingress.k8s.aws/stack-namespace: namespace`
   * `ingress.k8s.aws/stack-name: ingressName`
 * For Service, the following tags will be applied on all K8s resources:
   * `service.k8s.aws/stack-namespace: namespace`
   * `service.k8s.aws/stack-name: serviceName`
### For K8s resources, the following finalizers are used:
* For Ingresses within explicit IngressGroup: `group.ingress.k8s.aws/groupName`
* For Ingresses don't belong to explicit IngressGroup: `ingress.k8s.aws/resources`
* For Services: `service.k8s.aws/resources`
* For TargetGroupBindings: `elbv2.k8s.aws/resources`
### For pods behind targetGroupBindings with IP targetType, the following readinessGate will be injected:
* `target-health.elbv2.k8s.aws/targetGroupBindingName`

# additional changes:
1. support Tag on creation for TargetGroups.
2. preserve old tags on AWS resources provisioned by AWSALBLoadBalancerController(v1.1.3+), so that downgrade is support. 
3. normalize the namespace/name used in resource names. so that targetGroup won't be named like "k8s-xxxx--dde"(two continuous '-' within name).
4. standard all naming generation for resources created for Ingress and Service, especially:
    1. the LoadBalancer name of both ALB/NLB follows the same `k8s-.8{namespace}-.8{name}-.10{hash}` pattern. For IngressGroups, the name can be `k8s-.17{groupName}-.10{hash}`
    2. the TargetGroups are now named following similar pattern across ALB/NLB.
5. the resourceID of LoadBalancer for NLB stack is changed to `LoadBalancer`
6. use shared k8s.finalizerManager to handle finalizer logic for IngressGroup
7. abstract a TaggingManager for EC2 Tagging operations.
8. various code style corrections

# Test done:
1. create Ingress -> delete Ingress   (success)
2. create IngressGroup -> delete IngressGroup  (success)
3. create Ingress with long name  in long namespace -> delete Ingress  (success)
4. create Ingress with old controller -> disable old controller -> run new controller -> verify resource state 
    -> disable new controller -> delete TargetGroupBindings -> run old controller -> verify resource state  (success)
   
Fixes #1463

### CODE REVIEW

File: pkg/ingress/model_build_managed_sg.go [hunk 1]
```diff
@@ -2,7 +2,7 @@ package ingress
 
 import (
 	"context"
-	"crypto/md5"
+	"crypto/sha1"
```
Comment (kishorj) [inline pkg/ingress/model_build_managed_sg.go:5]: if md5 is not acceptable, sha1 would also not be. lets replace with sha256

Comment (M00nF1sh) [reply pkg/ingress/model_build_managed_sg.go]: updated with sha256 hashes :D

**Review by kishorj — APPROVED** [review]
