### PR TITLE
Multiple bug fixes and doc enhancements

### LINKED ISSUE #1140: Advanced routing option gives: failed to GC targetGroups due to failed to delete targetGroup due to ResourceInUse
Release: 1.1.5
Advanced routing option with weights on a TG is what I am trying to test. But I get error:

The below configuration did create 2 rules, however it is now trying to delete one of the preexisting TGS from those rules. Below configuration create 2 rules like this:

THEN
Forward to
caf3bb0c-5458b9d866d32d43ccc: 80 (80%)
caf3bb0c-497bf45e8963ca6ecd6: 20 (20%)
Group-level stickiness: 20 seconds

alb ingress logs
E0122 19:57:38.167233       1 controller.go:217] kubebuilder/controller "msg"="Reconciler error" "error"="failed to GC targetGroups due to failed to delete targetGroup due to ResourceInUse: Target group 'arn:aws:elasticloadbalancing:us-west-2:XXXX:targetgroup/caf3bb0c-5458b9d866d32d43ccc/db26700c342b16e8' is currently in use by a listener or a rule\n\tstatus code: 400, request id: 1935d805-83ec-472a-8823-19a72768ef69"  "controller"="alb-ingress-controller" "request"={"Namespace":"default","Name":"nginx-service-ip-ingress"}

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: "nginx-service-ip-ingress"
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internal
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/actions.forward-multiple-tg: >
      {"Type":"forward","ForwardConfig":{"TargetGroups":[{"TargetGroupArn":"arn:aws:elasticloadbalancing:us-west-2:XXXXX:targetgroup/caf3bb0c-5458b9d866d32d43ccc/db26700c342b16e8","Weight":80},{"ServiceName":"nginx-2","ServicePort":"80","Weight":20}],"TargetGroupStickinessConfig":{"Enabled":true,"DurationSeconds":20}}}
  labels:
    app: nginx-ingress
spec:
  rules:
    - host: nginx.service.eks4.internal.aws
      http:
        paths:
          - path: /*
            backend:
              serviceName: forward-multiple-tg
              servicePort: use-annotation

Questions:
- Why is the TG being deleted?
- Why are we getting this error?
- We need to do this in production without any impact on the existing ingress

### LINKED ISSUE #1149: Document HTTPS requirement for Cognito/OIDC authentication
If a user attempts to configure Cognito or OIDC authentication for an ALB ingress using the appropriate annotations, but fails to configure a TLS listener, the annotations will have no effect, and no error will be returned to the user or printed to the controller logs.  This leaves the user very confused as to why things aren't working.

Document this requirement in the docs, and provide some sort of error messaging that the user can use for debugging.

### LINKED ISSUE #1150: Multiple separate rules with the same target group
How to create multiple separate rules with the same target group which is defined as a service.
For example something like: 
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    alb.ingress.kubernetes.io/actions.ssl-redirect: '{"Type": "redirect", "RedirectConfig":
      { "Protocol": "HTTPS", "Port": "443", "StatusCode": "HTTP_301"}}'
    alb.ingress.kubernetes.io/certificate-arn: <certificate_arn>
    alb.ingress.kubernetes.io/conditions.k8s-service: |
      [{"Field":"http-header","HttpHeaderConfig":{"HttpHeaderName": "AnyHeaderName", "Values":["AnyHeaderValue"]}}]
    alb.ingress.kubernetes.io/conditions.k8s-service: |
      [{"Field":"source-ip","SourceIpConfig":{"Values":["1.1.1.1/1"]}}]
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS":443}]'
    alb.ingress.kubernetes.io/scheme: internet-facing
    kubernetes.io/ingress.class: alb
  labels:
    app.kubernetes.io/name:application-name
  name: some-web-ingress
spec:
  rules:
  - host: example.com
  - http:
      paths:
      - backend:
          serviceName: ssl-redirect
          servicePort: use-annotation
        path: /*
      - backend:
          serviceName: k8s-service
          servicePort: 443
        path: /*
```
I want to specify a few conditions **alb.ingress.kubernetes.io/conditions.k8s-service** for the same service name which will create different separate rules to the same target group, but the above solution doesn't work. 
A workaround  which I found here is to create a second service with different name, but pointing to the same resource and then use it in **alb.ingress.kubernetes.io/conditions.k8s-service2**. 
Workaround example I will post in comments bellow. 

P.S. Just to be more clear, in my case I dont want to create something like: 
```
alb.ingress.kubernetes.io/conditions.k8s-service: >
  [{"Field":"http-header","HttpHeaderConfig":{"HttpHeaderName": "AnyHeaderName", "Values":["AnyHeaderValue"]}},{"Field":"source-ip","SourceIpConfig":{"Values":["1.1.1.1/1"]}}]
```
because this creates multiple conditions in the same rule.

### LINKED ISSUE #1163: When running by target-type:ip on EKS, ingress targetgroup changes occur due to the increase or decrease of unrelated nodes ASG
We create ingress with target-type:ip on EKS, alb-ingress-controller modify target group when the increase or decrease of unrelated nodes(pod controlled taint and affinity) .

Is this the expected behavior?
The log of alb-ingress-controller with `-v = 4 ` is as follows.

```
I0212 00:54:45.133850       1 listener.go:162] util: DeepEqual([{    ForwardConfig: {      TargetGroupStickinessConfig: {        Enabled: false      },      TargetGroups: [{          TargetGroupArn: "arn:aws:elasticloadbalancing:ap-northeast-1:249XXXXXXXX:targetgroup/df1XXXX-1cf6af38ccfdbc5994f/e2fdb9XXXXX769a1",          Weight: 1        }]    },    Order: 1,    TargetGroupArn: "arn:aws:elasticloadbalancing:ap-northeast-1:249XXXXXXXX:targetgroup/df1XXXX-1cf6af38ccfdbc5994f/e2fdb9XXXXX769a1",    Type: "forward"  }], [{    ForwardConfig: {      TargetGroupStickinessConfig: {        Enabled: false      },      TargetGroups: [{          TargetGroupArn: "arn:aws:elasticloadbalancing:ap-northeast-1:249XXXXXXXX:targetgroup/df1XXXX-1cf6af38ccfdbc5994f/e2fdb9XXXXX769a1",          Weight: 1        }]    },    Order: 1,    Type: "forward"  }]) found inequality
I0212 00:54:45.133904       1 log.go:30] test-web/test-web-php: listener defaultActions needs modification: [{
I0212 00:54:45.133911       1 log.go:30] test-web/test-web-php:     ForwardConfig: {
I0212 00:54:45.133915       1 log.go:30] test-web/test-web-php:       TargetGroupStickinessConfig: {
I0212 00:54:45.133919       1 log.go:30] test-web/test-web-php:         Enabled: false
I0212 00:54:45.133923       1 log.go:30] test-web/test-web-php:       },
I0212 00:54:45.133928       1 log.go:30] test-web/test-web-php:       TargetGroups: [{
I0212 00:54:45.133932       1 log.go:30] test-web/test-web-php:           TargetGroupArn: "arn:aws:elasticloadbalancing:ap-northeast-1:249XXXXXXXX:targetgroup/df1XXXX-1cf6af38ccfdbc5994f/e2fdb9XXXXX769a1",
I0212 00:54:45.133936       1 log.go:30] test-web/test-web-php:           Weight: 1
I0212 00:54:45.133940       1 log.go:30] test-web/test-web-php:         }]
I0212 00:54:45.133945       1 log.go:30] test-web/test-web-php:     },
I0212 00:54:45.133949       1 log.go:30] test-web/test-web-php:     Order: 1,
I0212 00:54:45.133953       1 log.go:30] test-web/test-web-php:     TargetGroupArn: "arn:aws:elasticloadbalancing:ap-northeast-1:249XXXXXXXX:targetgroup/df1XXXX-1cf6af38ccfdbc5994f/e2fdb9XXXXX769a1",
I0212 00:54:45.133957       1 log.go:30] test-web/test-web-php:     Type: "forward"
I0212 00:54:45.133961       1 log.go:30] test-web/test-web-php:   }] => [{
I0212 00:54:45.133966       1 log.go:30] test-web/test-web-php:     ForwardConfig: {
I0212 00:54:45.133977       1 log.go:30] test-web/test-web-php:       TargetGroupStickinessConfig: {
I0212 00:54:45.133981       1 log.go:30] test-web/test-web-php:         Enabled: false
I0212 00:54:45.133987       1 log.go:30] test-web/test-web-php:       },
I0212 00:54:45.133994       1 log.go:30] test-web/test-web-php:       TargetGroups: [{
I0212 00:54:45.134007       1 log.go:30] test-web/test-web-php:           TargetGroupArn: "arn:aws:elasticloadbalancing:ap-northeast-1:249XXXXXXXX:targetgroup/df1XXXX-1cf6af38ccfdbc5994f/e2fdb9XXXXX769a1",
I0212 00:54:45.134013       1 log.go:30] test-web/test-web-php:           Weight: 1
I0212 00:54:45.134025       1 log.go:30] test-web/test-web-php:         }]
I0212 00:54:45.134032       1 log.go:30] test-web/test-web-php:     },
I0212 00:54:45.134039       1 log.go:30] test-web/test-web-php:     Order: 1,
I0212 00:54:45.134052       1 log.go:30] test-web/test-web-php:     Type: "forward"
I0212 00:54:45.134060       1 log.go:30] test-web/test-web-php:   }]
I0212 00:54:45.134070       1 listener.go:127] test-web/test-web-php: modifying listener 443, arn: arn:aws:elasticloadbalancing:ap-northeast-1:249XXXXXXXX:listener/app/df1XXXX-testweb-test-048b/fded59c73319227b/5bcf81e803022c96
I0212 00:54:45.203204       1 listener.go:162] util: DeepEqual([{    ForwardConfig: {      TargetGroupStickinessConfig: {        Enabled: false      },      TargetGroups: [{          TargetGroupArn: "arn:aws:elasticloadbalancing:ap-northeast-1:249XXXXXXXX:targetgroup/df1XXXX-1cf6af38ccfdbc5994f/e2fdb9XXXXX769a1",          Weight: 1        }]    },    Order: 1,    TargetGroupArn: "arn:aws:elasticloadbalancing:ap-northeast-1:249XXXXXXXX:targetgroup/df1XXXX-1cf6af38ccfdbc5994f/e2fdb9XXXXX769a1",    Type: "forward"  }], [{    ForwardConfig: {      TargetGroupStickinessConfig: {        Enabled: false      },      TargetGroups: [{          TargetGroupArn: "arn:aws:elasticloadbalancing:ap-northeast-1:249XXXXXXXX:targetgroup/df1XXXX-1cf6af38ccfdbc5994f/e2fdb9XXXXX769a1",          Weight: 1        }]    },    Order: 1,    Type: "forward"  }]) found inequality
I0212 00:54:45.203259       1 log.go:30] test-web/test-web-php: listener defaultActions needs modification: [{
I0212 00:54:45.203266       1 log.go:30] test-web/test-web-php:     ForwardConfig: {
I0212 00:54:45.203270       1 log.go:30] test-web/test-web-php:       TargetGroupStickinessConfig: {
I0212 00:54:45.203274       1 log.go:30] test-web/test-web-php:         Enabled: false
I0212 00:54:45.203278       1 log.go:30] test-web/test-web-php:       },
I0212 00:54:45.203282       1 log.go:30] test-web/test-web-php:       TargetGroups: [{
I0212 00:54:45.203286       1 log.go:30] test-web/test-web-php:           TargetGroupArn: "arn:aws:elasticloadbalancing:ap-northeast-1:249XXXXXXXX:targetgroup/df1XXXX-1cf6af38ccfdbc5994f/e2fdb9XXXXX769a1",
I0212 00:54:45.203291       1 log.go:30] test-web/test-web-php:           Weight: 1
I0212 00:54:45.203295       1 log.go:30] test-web/test-web-php:         }]
I0212 00:54:45.203299       1 log.go:30] test-web/test-web-php:     },
I0212 00:54:45.203303       1 log.go:30] test-web/test-web-php:     Order: 1,
I0212 00:54:45.203307       1 log.go:30] test-web/test-web-php:     TargetGroupArn: "arn:aws:elasticloadbalancing:ap-northeast-1:249XXXXXXXX:targetgroup/df1XXXX-1cf6af38ccfdbc5994f/e2fdb9XXXXX769a1",
I0212 00:54:45.203312       1 log.go:30] test-web/test-web-php:     Type: "forward"
I0212 00:54:45.203316       1 log.go:30] test-web/test-web-php:   }] => [{
I0212 00:54:45.203320       1 log.go:30] test-web/test-web-php:     ForwardConfig: {
I0212 00:54:45.203335       1 log.go:30] test-web/test-web-php:       TargetGroupStickinessConfig: {
I0212 00:54:45.203339       1 log.go:30] test-web/test-web-php:         Enabled: false
I0212 00:54:45.203343       1 log.go:30] test-web/test-web-php:       },
I0212 00:54:45.203348       1 log.go:30] test-web/test-web-php:       TargetGroups: [{
I0212 00:54:45.203352       1 log.go:30] test-web/test-web-php:           TargetGroupArn: "arn:aws:elasticloadbalancing:ap-northeast-1:249XXXXXXXX:targetgroup/df1XXXX-1cf6af38ccfdbc5994f/e2fdb9XXXXX769a1",
I0212 00:54:45.203356       1 log.go:30] test-web/test-web-php:           Weight: 1
I0212 00:54:45.203360       1 log.go:30] test-web/test-web-php:         }]
I0212 00:54:45.203365       1 log.go:30] test-web/test-web-php:     },
I0212 00:54:45.203369       1 log.go:30] test-web/test-web-php:     Order: 1,
I0212 00:54:45.203373       1 log.go:30] test-web/test-web-php:     Type: "forward"
I0212 00:54:45.203377       1 log.go:30] test-web/test-web-php:   }]
I0212 00:54:45.203385       1 listener.go:127] test-web/test-web-php: modifying listener 80, arn: arn:aws:elasticloadbalancing:ap-northeast-1:249XXXXXXXX:listener/app/df1XXXX-testweb-test-048b/fded59c73319227b/ff2a357a5fafc78a
I0212 00:54:45.906394       1 controller.go:236] kubebuilder/controller "level"=1 "msg"="Successfully Reconciled"  "controller"="alb-ingress-controller" "request"={"Namespace":"test-web","Name":"test-web-php"}
```

### PR DESCRIPTION
**Pull request by M00nF1sh**
The PR is separated into 6 independent commit: (review each one individually by click on "Commits" tab. 

1. `fix default action comparison`: Fix #1163 . 
    The default action from ALB contains both targetGroupARN in top level Action structure, and also contain targetGroupARN in forwardAction structure. While desiredAction build only contains it in forwardAction structure. Use dedicated compare method instead of deepEqual to avoid unnecessary modification. 
2. `issue warning when an targetGroup for k8s service is referenced by ARN`: Fix #1140
   There are users used TargetGroupArn in action configuration even if the targetGroup is created for a k8s service by controller. The controller will try to delete that targetGroup(though the deletion will fail due to dependencies).
   This commit will issue a warning to user and bypass deletion under such misusage.
3. `various docs enhancements`: close #1150, close #1149 
    1. make it clear authentication is only supported for HTTPS listener
    2. make it clear that `conditions` annotation is supported for both normal serviceName and annotation based action name.
    3. make it clear that forward-multiple-tg supports multiple k8s service as well.
    4. fix `make docs-serve` and `make docs-deploy` by install dependencies first.
4. `set default log level to be 2 for more verbose message`: sets default log level to 2, which will emit "successfully reconciled" message from controller-runtime, which is useful for most ppl.
5. `make subnet resolve message more clear`: make the subnet tagging requirement message more clear: 
   ```
   failed to build LoadBalancer configuration due to failed to resolve 2 qualified subnet for ALB. Subnets must contains these tags: 'kubernetes.io/cluster/m00nf1sh-dev': ['shared' or 'owned'] and 'kubernetes.io/role/elb': ['' or '1']. See https://kubernetes-sigs.github.io/aws-alb-ingress-controller/guide/controller/config/#subnet-auto-discovery for more details. Resolved qualified subnets: '[]'"
   ```
6. `bug fix for pod readiness gate`: capture 2 edge case that is not captured in original podReadinessGate PR

### CODE REVIEW

File: internal/alb/tg/targetgroup_group.go [hunk 1]
```diff
@@ -85,17 +88,23 @@ func (controller *defaultGroupController) GC(ctx context.Context, tgGroup Target
...
 		return fmt.Errorf("failed to get targetGroups due to %v", err)
 	}
-	currentTgArns := sets.NewString(arns...)
-	unusedTgArns := currentTgArns.Difference(usedTgArns)
-	for arn := range unusedTgArns {
+	currentServiceTGARNs := sets.NewString(arns...)
+	unusedServiceTGARNs := currentServiceTGARNs.Difference(usedServiceTGARNs)
+	for arn := range unusedServiceTGARNs {
+		if usedExternalTGARNs.Has(arn) {
+			albctx.GetEventf(ctx)(corev1.EventTypeWarning, "Warning", "targetGroup created for k8s service should be referenced by serviceName and servicePort instead of TargetGroupARN: %s", arn)
```
Comment (jaypipes) [inline internal/alb/tg/targetgroup_group.go]: Is this something that is actionable, though? The message above doesn't seem to explain *why* this is a warning.

Maybe this should just be an INFO-level log message and perhaps change the message to something like "Ignoring targetGroup XXX during garbage collection because targetGroupARN is set, indicating it was not created by ALB Ingress Controller."?

File: internal/alb/tg/targethealth.go [hunk 2]
```diff
@@ -202,6 +202,9 @@ func (c *targetHealthController) reconcilePodConditions(ctx context.Context, tgA
 
 	for i, target := range targetsToReconcile {
 		pod := pods[i]
+		if pod == nil {
+			continue
+		}
```
Comment (jaypipes) [inline internal/alb/tg/targethealth.go]: Putting this comment here because GH doesn't let me add a comment about a commit summary/description...

In this commit message, you misspelled "readiness" as "readness". Also, the commit message does not explain *what* is being fixed by the commit's contents, so it's impossible to tell from the git log/history what these code changes are meant to address.

File: internal/ingress/backend/endpoint.go [hunk 3]
```diff
@@ -160,7 +160,7 @@ func (resolver *endpointResolver) resolveIP(ingress *extensions.Ingress, backend
 			// we need to loop over all unready pods to check if the ALB readiness gate is the only condition preventing the pod from being ready;
 			// if this is the case, we return the pod as a desired target although its not in `Addresses`
 			for _, epAddr := range epSubset.NotReadyAddresses {
-				if epAddr.TargetRef == nil {
+				if epAddr.TargetRef == nil || epAddr.TargetRef.Kind != "Pod" {
```
Comment (jaypipes) [inline internal/ingress/backend/endpoint.go]: is there any unit test change that corresponds to this?

File: internal/alb/tg/targetgroup_group.go (hunk 1 above)
Comment (M00nF1sh) [reply internal/alb/tg/targetgroup_group.go]: Hi, jay, yes. This action is actionable. If the targetGroup is created by the controller, then user shouldn't use a ARN to reference it. It's stated in docs as well https://kubernetes-sigs.github.io/aws-alb-ingress-controller/guide/ingress/annotation/#actions "use ARN in forward Action".

File: internal/alb/tg/targethealth.go (hunk 2 above)
Comment (M00nF1sh) [reply internal/alb/tg/targethealth.go]: Thanks. Updated the commit message to be 'bug fix for edge cases not covered by pod readness gate PR #955'
It's addressing missing parts of https://github.com/kubernetes-sigs/aws-alb-ingress-controller/pull/955. Where the resolved pod from endpoint IP can be nil when pod is not found. This can happen since the endpoint resolve and reserve resolve is based on live pod data store in real time and can be inconsistent.

File: internal/ingress/backend/endpoint.go (hunk 3 above)
Comment (M00nF1sh) [reply internal/ingress/backend/endpoint.go]: added unit test

File: internal/alb/tg/targethealth.go (hunk 2 above)
Comment (SaranBalaji90) [reply internal/alb/tg/targethealth.go]: I see that you added unit test for the other change, can you add one for this as well as for targetgroup_group.go changes?

Comment (M00nF1sh) [reply internal/alb/tg/targethealth.go]: added :D
